### ISSUE TITLE
Custom controller gains

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/kuka-lwr#6]
The gains must be specified in the YAML file configuration, and ideally, dynamically re-configurable. Default values should provide a decent performance.

**Comment by enricocorvaglia** [comment]
Hi guys, @carlosjoserg @Tabjones @manuelbonilla 
please review the implementation of the OneTaskInverseKinematics controller, now it reads the PID gains from the lwr_controllers.yaml and it has a topic call to update them (see README for command). Tell me if you have comments, if it's fine in the next days I will do it for the other controllers.

**Comment by Tabjones** [comment]
So technically you wrote the gains into a yaml and read them instead of hardcoding them into the source.
Nice work, i'll test it on the lwr as soon as i can.

**Comment by carlosjoserg** [comment]
It looks fine to me. However, I see you are using the pid class from ros control that already has an implementation for this, and it uses a dynamic reconfigure to set the gains, and we should make the most of it.

I would suggest to initialize each of the pid's like in line 68 of the [position controller](https://github.com/ros-controls/ros_controllers/blob/indigo-devel/effort_controllers/src/joint_position_controller.cpp), that is, in our case, something like:
```c++
// Load PID Controller using gains set on parameter server
std::string pid_("pid_");
for (int i = 0; i < kdl_chain_.getNrOfJoints(); ++i)
{
    if (!PIDs_[i].init(ros::NodeHandle(n, pid_ +
        joint_handles_.getJoint(i).getName() )))
    {
        ROS_ERROR("Error initializing the PIDs");
        return false;
    }
}
```

That why, the yaml file can be written like:
```yaml
  OneTaskInverseKinematics: 
    type: lwr_controllers/OneTaskInverseKinematics
    root_name: world
    tip_name: lwr_7_link
    pid_lwr_1_joint: {p: 250,  i: 10, d: 30}
    pid_lwr_1_joint: {p: 220,  i: 10, d: 30}
    pid_lwr_2_joint: {p: 150,  i: 6, d: 20}
    pid_lwr_3_joint: {p: 150,  i: 5, d: 12}
    pid_lwr_4_joint: {p: 90,  i: 5, d: 10}
    pid_lwr_5_joint: {p: 40,  i: 5, d: 7}
    pid_lwr_6_joint: {p: 15,  i: 2, d: 5}
```
